//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandstalkerGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandstalkerGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DefaultPersonalSettings {
            get {
                object obj = ResourceManager.GetObject("DefaultPersonalSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DefaultPreset {
            get {
                object obj = ResourceManager.GetObject("DefaultPreset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hud {
            get {
                object obj = ResourceManager.GetObject("Hud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HudMask {
            get {
                object obj = ResourceManager.GetObject("HudMask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;0&quot;: {
        ///    &quot;name&quot;: &quot;EkeEke&quot;,
        ///    &quot;goldValue&quot;: 20
        ///  },
        ///  &quot;1&quot;: {
        ///    &quot;name&quot;: &quot;Magic Sword&quot;,
        ///    &quot;goldValue&quot;: 300
        ///  },
        ///  &quot;2&quot;: {
        ///    &quot;name&quot;: &quot;Sword of Ice&quot;,
        ///    &quot;goldValue&quot;: 300
        ///  },
        ///  &quot;3&quot;: {
        ///    &quot;name&quot;: &quot;Thunder Sword&quot;,
        ///    &quot;goldValue&quot;: 500
        ///  },
        ///  &quot;4&quot;: {
        ///    &quot;name&quot;: &quot;Sword of Gaia&quot;,
        ///    &quot;goldValue&quot;: 300
        ///  },
        ///  &quot;5&quot;: {
        ///    &quot;name&quot;: &quot;Fireproof&quot;,
        ///    &quot;goldValue&quot;: 150
        ///  },
        ///  &quot;6&quot;: {
        ///    &quot;name&quot;: &quot;Iron Boots&quot;,
        ///    &quot;goldValue&quot;: 150
        ///  },
        ///  &quot;7&quot;: {
        ///    &quot;name&quot;: &quot;Healing Boots&quot;,
        ///    &quot;goldVa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LakeShrinePath {
            get {
                object obj = ResourceManager.GetObject("LakeShrinePath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///    &lt;system:String x:Key=&quot;ResourceDictionaryName&quot;&gt;Localisation-en-US&lt;/system:String&gt;
        ///
        ///    &lt;system:String x:Key=&quot;Title&quot;&gt;Randstalker GUI&lt;/system:String&gt;
        ///
        ///    &lt;!-- Common --&gt;
        ///    &lt;system:String x:Key=&quot;NewFile&quot;&gt;New file&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;NewDirect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocalisationDictionary_en_US {
            get {
                return ResourceManager.GetString("LocalisationDictionary.en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///    &lt;system:String x:Key=&quot;ResourceDictionaryName&quot;&gt;Localisation-fr-FR&lt;/system:String&gt;
        ///
        ///    &lt;system:String x:Key=&quot;Title&quot;&gt;Randstalker GUI&lt;/system:String&gt;
        ///
        ///    &lt;!-- Common --&gt;
        ///    &lt;system:String x:Key=&quot;NewFile&quot;&gt;Nouveau fichier&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;Ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocalisationDictionary_fr_FR {
            get {
                return ResourceManager.GetString("LocalisationDictionary.fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nigel {
            get {
                object obj = ResourceManager.GetObject("Nigel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NigelEditablePixels {
            get {
                object obj = ResourceManager.GetObject("NigelEditablePixels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;randstlakerExeFilePath&quot;: &quot;&quot;,
        ///  &quot;presetsDirectoryPath&quot;: &quot;&quot;,
        ///  &quot;lastUsedPresetFilePath&quot;: &quot;preset.json&quot;,
        ///  &quot;personalSettingsDirectoryPath&quot;: &quot;&quot;,
        ///  &quot;lastUsedPersonalSettingsFilePath&quot;: &quot;personal_settings.json&quot;,
        ///  &quot;inputRomFilePath&quot;: &quot;&quot;,
        ///  &quot;outputRomDirectoryPath&quot;: &quot;&quot;
        ///}
        ///.
        /// </summary>
        internal static string UserConfig {
            get {
                return ResourceManager.GetString("UserConfig", resourceCulture);
            }
        }
    }
}
